---
Name: plato-silverstripe-gallery
After:
  - 'framework/*'
  - 'cms/*'
---
GalleryPage:
  ItemLimit: 100
  VideoAllowed: false
  icon: 'plato-gallery/images/gallerypage.png'
GalleryPage_Controller:
